### PR TITLE
Add max retry for upstart waiting

### PR DESCRIPTION
**Pull request by helgi**

### CODE REVIEW

**Comment by nathwill** [comment]
i'm starting to wonder if this whole post-start cycle might not be better implemented directly in the chef recipe in a ruby_block for the minimal number of users where this might be needed. thoughts?

**Comment by helgi** [comment]
IMO that's too much of a reliance on Chef for things that can happen outside of Chef

For example I have a deployment system that has no awareness of Chef that restarts App Server (different languages) that hooks into Monit in one way or another.

This might be more of a personal preference as well but I think a `ruby_block` is a code smell

**Comment by nathwill** [comment]
okley dokley. thanks for the PR!

**Comment by helgi** [comment]
Thanks @nathwill :)

**Comment by nathwill** [comment]
@helgi thank you! the last several PRs are now live on the Supermarket in version 2.1.0 :tada:

**Pull request merged**
